### ISSUE TITLE
Bootstrap script should package hab components

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/on-prem-builder#72]
Currently, we are only packaging in core packages that do not include the hab binary, supervisor, exporters, etc. We should update the script to pull these in, and push up a new bootstrap bundle (which will update us to the latest core plans as well).

**Comment by raskchanky** [comment]
@chefsalim Is there a specific list of everything we want to include?  I can just iterate through everything in https://github.com/habitat-sh/habitat/tree/master/components that has a `plan.sh` and try to download that, but I wasn't sure if we wanted to be a bit more intentional about specific packages?
